name: 🚀 Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install pnpm Dependencies
        run: npx pnpm i

      - name: Build
        run: npx pnpm run build

      - name: Build Docs
        run: npx pnpm run docs:build

      - name: Install deployctl
        run: deno install -Arf https://deno.land/x/deploy/deployctl.ts

      - name: Deploy
        run: deno task deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
